//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hapvida.ExternalIntegration.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HapvidaExternalIntegrationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public HapvidaExternalIntegrationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hapvida.ExternalIntegration.Domain.Resources.HapvidaExternalIntegrationResource", typeof(HapvidaExternalIntegrationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP não pode ser vazio..
        /// </summary>
        public static string ZipCode_Empty {
            get {
                return ResourceManager.GetString("ZipCode_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP deve conter apenas dígitos..
        /// </summary>
        public static string ZipCode_InvalidCharacters {
            get {
                return ResourceManager.GetString("ZipCode_InvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP deve conter exatamente {0} dígitos..
        /// </summary>
        public static string ZipCode_InvalidLength {
            get {
                return ResourceManager.GetString("ZipCode_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP deve conter 8 dígitos. Valor recebido: {0}.
        /// </summary>
        public static string Cep_InvalidFormat {
            get {
                return ResourceManager.GetString("Cep_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP {0} não foi encontrado em nenhum provedor..
        /// </summary>
        public static string Cep_NotFound {
            get {
                return ResourceManager.GetString("Cep_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP inválido.
        /// </summary>
        public static string Cep_InvalidTitle {
            get {
                return ResourceManager.GetString("Cep_InvalidTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP não encontrado.
        /// </summary>
        public static string Cep_NotFoundTitle {
            get {
                return ResourceManager.GetString("Cep_NotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrasilAPI provider não encontrado.
        /// </summary>
        public static string Provider_BrasilApiNotFound {
            get {
                return ResourceManager.GetString("Provider_BrasilApiNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViaCEP provider não encontrado.
        /// </summary>
        public static string Provider_ViaCepNotFound {
            get {
                return ResourceManager.GetString("Provider_ViaCepNotFound", resourceCulture);
            }
        }
    }
}
